package com.iron_link_gym.db;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class DBConnection {
    private static final String URL      = "jdbc:oracle:thin:@localhost:1521:XE";
    private static final String USER     = "system";
    private static final String PASSWORD = "2006";

    private static Connection connection = null;

    public static Connection getConnection() throws SQLException {
        if (connection == null || connection.isClosed()) {
            connection = DriverManager.getConnection(URL, USER, PASSWORD);
        }
        return connection;
    }

    /** Called once at application startup to create all tables if they don't exist. */
    public static void initSchema() {
        try {
            Connection conn = getConnection();
            createIfAbsent(conn, "MEMBERS",
                "CREATE TABLE MEMBERS (" +
                "  member_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "  full_name    VARCHAR2(100) NOT NULL," +
                "  phone        VARCHAR2(20)," +
                "  email        VARCHAR2(100)," +
                "  date_joining DATE DEFAULT SYSDATE," +
                "  medical_notes VARCHAR2(500)" +
                ")");

            createIfAbsent(conn, "TRAINERS",
                "CREATE TABLE TRAINERS (" +
                "  trainer_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "  full_name      VARCHAR2(100) NOT NULL," +
                "  phone          VARCHAR2(20)," +
                "  specialization VARCHAR2(100)," +
                "  timings        VARCHAR2(100)" +
                ")");

            createIfAbsent(conn, "PLANS",
                "CREATE TABLE PLANS (" +
                "  plan_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "  plan_name      VARCHAR2(100) NOT NULL," +
                "  plan_type      VARCHAR2(50)," +
                "  duration_days  NUMBER NOT NULL," +
                "  price          NUMBER(10,2) NOT NULL," +
                "  is_active      CHAR(1) DEFAULT 'Y'" +
                ")");

            createIfAbsent(conn, "MEMBERSHIPS",
                "CREATE TABLE MEMBERSHIPS (" +
                "  subscription_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "  member_id       NUMBER NOT NULL REFERENCES MEMBERS(member_id) ON DELETE CASCADE," +
                "  plan_id         NUMBER NOT NULL REFERENCES PLANS(plan_id)," +
                "  trainer_id      NUMBER REFERENCES TRAINERS(trainer_id)," +
                "  start_date      DATE NOT NULL," +
                "  end_date        DATE NOT NULL," +
                "  status          VARCHAR2(20) DEFAULT 'Active'" +
                ")");

            createIfAbsent(conn, "ATTENDANCE",
                "CREATE TABLE ATTENDANCE (" +
                "  attendance_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "  member_id      NUMBER NOT NULL REFERENCES MEMBERS(member_id) ON DELETE CASCADE," +
                "  checkin_date   DATE DEFAULT SYSDATE," +
                "  checkin_time   TIMESTAMP DEFAULT SYSTIMESTAMP," +
                "  checkout_time  TIMESTAMP" +
                ")");
            createView(conn, "MEMBERSHIP_DETAILS",
                    "CREATE OR REPLACE VIEW membership_details AS " +
                    "SELECT " +
                    "  ms.subscription_id, " +
                    "  ms.member_id, " +
                    "  m.full_name AS full_name, " +
                    "  ms.plan_id, " +
                    "  p.plan_name AS plan_name, " +
                    "  NVL(ms.trainer_id, 0) AS trainer_id, " +
                    "  NVL(t.full_name, 'None') AS trainer_name, " +
                    "  ms.start_date, " +
                    "  ms.end_date, " +
                    "  ms.status " +
                    "FROM MEMBERSHIPS ms " +
                    "LEFT JOIN MEMBERS m ON ms.member_id = m.member_id " +
                    "LEFT JOIN PLANS p ON ms.plan_id = p.plan_id " +
                    "LEFT JOIN TRAINERS t ON ms.trainer_id = t.trainer_id"
                );
                
                createTrigger(conn, "AUTO_EXPIRE_MEMBERSHIP",
                    "CREATE OR REPLACE TRIGGER auto_expire_membership " +
                    "BEFORE INSERT OR UPDATE ON MEMBERSHIPS " +
                    "FOR EACH ROW " +
                    "BEGIN " +
                    "    IF :NEW.end_date IS NOT NULL AND :NEW.end_date < SYSDATE THEN " +
                    "        :NEW.status := 'Expired'; " +
                    "    END IF; " +
                    "END;"
                );

                createProcedure(conn, "CHECK_IN_MEMBER",
                    "CREATE OR REPLACE PROCEDURE check_in_member(p_member_id NUMBER) " +
                    "AS " +
                    "    v_count NUMBER; " +
                    "BEGIN " +
                    "    SELECT COUNT(*) INTO v_count " +
                    "    FROM ATTENDANCE " +
                    "    WHERE member_id = p_member_id " +
                    "    AND TRUNC(checkin_date) = TRUNC(SYSDATE); " +
                    "    IF v_count = 0 THEN " +
                    "        INSERT INTO ATTENDANCE(member_id, checkin_date, checkin_time) " +
                    "        VALUES(p_member_id, TRUNC(SYSDATE), SYSTIMESTAMP); " +
                    "    END IF; " +
                    "END;"
                );
                
                createProcedure(conn, "TRAINER_LOAD",
                    "CREATE OR REPLACE PROCEDURE trainer_load AS " +
                    "CURSOR c_tr IS SELECT trainer_id, full_name FROM TRAINERS; " +
                    "v_count NUMBER; " +
                    "BEGIN " +
                    "FOR rec IN c_tr LOOP " +
                    "SELECT COUNT(*) INTO v_count FROM MEMBERSHIPS WHERE trainer_id = rec.trainer_id; " +
                    "DBMS_OUTPUT.PUT_LINE(rec.full_name || ' → ' || v_count || ' members'); " +
                    "END LOOP; " +
                    "END;"
                );              

            System.out.println("[DBConnection] Schema initialised successfully.");
        } catch (SQLException e) {
            System.err.println("[DBConnection] Schema init error: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private static void createView(Connection conn, String viewName, String ddl) throws SQLException {
        try (Statement stmt = conn.createStatement()) {
            stmt.executeUpdate(ddl);
            System.out.println("[DBConnection] Created/Updated view: " + viewName);
        }
    }

    private static void createProcedure(Connection conn, String name, String ddl) throws SQLException {
        try (Statement stmt = conn.createStatement()) {
            stmt.executeUpdate(ddl);
            System.out.println("[DBConnection] Created/Updated procedure: " + name);
        }
    }                                   

    private static void createTrigger(Connection conn, String triggerName, String ddl) throws SQLException {
        try (Statement stmt = conn.createStatement()) {
            stmt.executeUpdate(ddl);
            System.out.println("[DBConnection] Created/Updated trigger: " + triggerName);
        }
    }

    private static void createIfAbsent(Connection conn, String tableName, String ddl) throws SQLException {
        DatabaseMetaData meta = conn.getMetaData();
        // Oracle stores unquoted names in upper-case
        ResultSet rs = meta.getTables(null, null, tableName.toUpperCase(), new String[]{"TABLE"});
        if (!rs.next()) {
            try (Statement stmt = conn.createStatement()) {
                stmt.executeUpdate(ddl);
                System.out.println("[DBConnection] Created table: " + tableName);
            }
        } else {
            System.out.println("[DBConnection] Table already exists: " + tableName);
        }
        rs.close();
    }

    public static void closeConnection() throws SQLException {
        if (connection != null && !connection.isClosed()) {
            connection.close();
        }
    }
}
