package com.iron_link_gym.db;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class DBConnection {
    private static final String URL      = "jdbc:oracle:thin:@localhost:1521:XE";
    private static final String USER     = "system";
    private static final String PASSWORD = "orca30805";

    private static Connection connection = null;

    public static Connection getConnection() throws SQLException {
        if (connection == null || connection.isClosed()) {
            connection = DriverManager.getConnection(URL, USER, PASSWORD);
        }
        return connection;
    }

    /** Called once at application startup to create all tables if they don't exist. */
    public static void initSchema() {
        try {
            Connection conn = getConnection();
            createIfAbsent(conn, "MEMBERS",
                "CREATE TABLE MEMBERS (" +
                "  member_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "  full_name    VARCHAR2(100) NOT NULL," +
                "  phone        VARCHAR2(20)," +
                "  email        VARCHAR2(100)," +
                "  date_joining DATE DEFAULT SYSDATE," +
                "  medical_notes VARCHAR2(500)" +
                ")");

            createIfAbsent(conn, "TRAINERS",
                "CREATE TABLE TRAINERS (" +
                "  trainer_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "  full_name      VARCHAR2(100) NOT NULL," +
                "  phone          VARCHAR2(20)," +
                "  specialization VARCHAR2(100)" +
                ")");

            createIfAbsent(conn, "PLANS",
                "CREATE TABLE PLANS (" +
                "  plan_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "  plan_name      VARCHAR2(100) NOT NULL," +
                "  plan_type      VARCHAR2(50)," +
                "  duration_days  NUMBER NOT NULL," +
                "  price          NUMBER(10,2) NOT NULL," +
                "  is_active      CHAR(1) DEFAULT 'Y'" +
                ")");

            createIfAbsent(conn, "MEMBERSHIPS",
                "CREATE TABLE MEMBERSHIPS (" +
                "  subscription_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "  member_id       NUMBER NOT NULL REFERENCES MEMBERS(member_id) ON DELETE CASCADE," +
                "  plan_id         NUMBER NOT NULL REFERENCES PLANS(plan_id)," +
                "  trainer_id      NUMBER REFERENCES TRAINERS(trainer_id)," +
                "  start_date      DATE NOT NULL," +
                "  end_date        DATE NOT NULL," +
                "  status          VARCHAR2(20) DEFAULT 'Active'" +
                ")");

            createIfAbsent(conn, "PAYMENTS",
                "CREATE TABLE PAYMENTS (" +
                "  payment_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "  subscription_id NUMBER NOT NULL REFERENCES MEMBERSHIPS(subscription_id) ON DELETE CASCADE," +
                "  amount          NUMBER(10,2) NOT NULL," +
                "  payment_date    DATE DEFAULT SYSDATE," +
                "  payment_method  VARCHAR2(50)" +
                ")");

            createIfAbsent(conn, "ATTENDANCE",
                "CREATE TABLE ATTENDANCE (" +
                "  attendance_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "  member_id      NUMBER NOT NULL REFERENCES MEMBERS(member_id) ON DELETE CASCADE," +
                "  checkin_date   DATE DEFAULT SYSDATE," +
                "  checkin_time   TIMESTAMP DEFAULT SYSTIMESTAMP," +
                "  checkout_time  TIMESTAMP" +
                ")");

            System.out.println("[DBConnection] Schema initialised successfully.");
        } catch (SQLException e) {
            System.err.println("[DBConnection] Schema init error: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private static void createIfAbsent(Connection conn, String tableName, String ddl) throws SQLException {
        DatabaseMetaData meta = conn.getMetaData();
        // Oracle stores unquoted names in upper-case
        ResultSet rs = meta.getTables(null, null, tableName.toUpperCase(), new String[]{"TABLE"});
        if (!rs.next()) {
            try (Statement stmt = conn.createStatement()) {
                stmt.executeUpdate(ddl);
                System.out.println("[DBConnection] Created table: " + tableName);
            }
        } else {
            System.out.println("[DBConnection] Table already exists: " + tableName);
        }
        rs.close();
    }

    public static void closeConnection() throws SQLException {
        if (connection != null && !connection.isClosed()) {
            connection.close();
        }
    }
}
